[package]
name = "rbspy-testdata"
version = "0.1.10"
authors = ["Kamal Marhubi <kamal@marhubi.com>", "Adam Jensen <adam@acj.sh>"]
description = "Test data for rbspy"
license = "MIT"
repository = "https://github.com/rbspy/rbspy-testdata"
homepage = "https://github.com/rbspy/rbspy-testdata"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0"
flate2 = "1.0.28"
goblin = "0.7.1"
libc = "0.2.15"
remoteprocess = "0.4.3"
